### ISSUE TITLE
Link to chats in each note?

### ISSUE THREAD

**Issue by halfcab1981** [Superkikim/nexus-ai-chat-importer#8]
Any chance you could add a link to the original URL for the chat in attributes of the note?

I have a command line tool that exports GPT chats to markdown but it is much more manual than your tool here. Would be great to have a reference back to the original chat though, so you can jump back into it. Otherwise great little tool!

**Comment by Superkikim** [comment]
Done. Check the master branch. 

Lot of changes. 

Note that you will have to reimport your conversations as I added metadata for this to work efficiently.  

- Delete your archive folder
- Remove the plugin 
- Follow documentation

NB: plugin name has changed. Read installation paragraph in documentation to be accurate

**Comment by halfcab1981** [comment]
Thanks so much, will give it a try!

**Comment by halfcab1981** [comment]
@Superkikim what am I doing wrong? I have the metadata now, but still not the URL

<img width="488" alt="image" src="https://github.com/user-attachments/assets/b43a9e20-f041-4034-b450-01417a580e89">

**Comment by Superkikim** [comment]
> @Superkikim what am I doing wrong? I have the metadata now, but still not the URL
> 

Click on the file title. Not the heading.

I'll try to make it more obvious soon to improve user experience.

![image](https://github.com/user-attachments/assets/71dce5bf-6139-4837-9aad-c5b2a98a271e)

**Comment by halfcab1981** [comment]
Got it! Nice one, thanks that will work well for me.
